### PR TITLE
add PHP7.2 to stable10

### PR DESCRIPTION
**Pull request by davitol**
add PHP7.2 to stable10

### CODE REVIEW

**Comment by phil-davis** [comment]
@davitol are you still going to work on this?
I see it in my list of PRs waiting for review.

**Comment by davitol** [comment]
> @davitol are you still going to work on this?
> I see it in my list of PRs waiting for review.

Not in the sort term, i'm focus in other stuff now. If you want to take over feel free.

**Comment by PVince81** [comment]
this isn't scheduled, please ignore for now.

I'll add it to a future sprint

**Comment by phil-davis** [comment]
This will get implemented as part of issue #28 
At the moment in Travis it has the catch-22 related to PHPunit 8.0.* described in https://github.com/owncloud/files_external_ftp/pull/33#issue-252975176
That stops us (easily) running unit tests against core `stable10` in Travis.
So we may as well close this PR.

**Comment by phil-davis** [comment]
Mysterious - most of the Travis CI passes, but actually it does not run any `phpunit` tests:
```
$ phpunit --version
PHPUnit 8.0.2 by Sebastian Bergmann and contributors.
The command "phpunit --version" exited with 0.
0.16s$ phpunit --configuration phpunit.xml
The command "phpunit --configuration phpunit.xml" exited with 0.
```
https://travis-ci.org/owncloud/files_external_ftp/jobs/502509419
???

Now I want to investigate and understand what is happening.

**Comment by phil-davis** [comment]
Done in PR #36

**Pull request closed without merging**
